,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas/issues/45631,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45631/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45631/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45631/events,https://github.com/pandas-dev/pandas/pull/45631,1114637540,PR_kwDOAA0YD84xmNNh,45631,Backport PR #45628 on branch 1.4.x (CI/TST: Call join on server process test),"{'login': 'meeseeksmachine', 'id': 39504233, 'node_id': 'MDQ6VXNlcjM5NTA0MjMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/39504233?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/meeseeksmachine', 'html_url': 'https://github.com/meeseeksmachine', 'followers_url': 'https://api.github.com/users/meeseeksmachine/followers', 'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}', 'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions', 'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs', 'repos_url': 'https://api.github.com/users/meeseeksmachine/repos', 'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}', 'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}, {'id': 49381477, 'node_id': 'MDU6TGFiZWw0OTM4MTQ3Nw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Network', 'name': 'IO Network', 'color': 'e4a5f1', 'default': False, 'description': 'Local or Cloud (AWS, GCS, etc.) IO Issues'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/93', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93/labels', 'id': 7593147, 'node_id': 'MI_kwDOAA0YD84Ac9y7', 'number': 93, 'title': '1.4.1', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 22, 'state': 'open', 'created_at': '2022-01-20T14:43:52Z', 'updated_at': '2022-01-26T05:12:08Z', 'due_on': '2022-02-12T08:00:00Z', 'closed_at': None}",0,2022-01-26T05:12:07Z,2022-01-26T05:12:08Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45631', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45631', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45631.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45631.patch', 'merged_at': None}",Backport PR #45628: CI/TST: Call join on server process test,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45631/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45631/timeline,
1,https://api.github.com/repos/pandas-dev/pandas/issues/45630,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45630/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45630/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45630/events,https://github.com/pandas-dev/pandas/issues/45630,1114594387,I_kwDOAA0YD85Cb1xT,45630,BUG: read_csv with `memory_map=True` on BytesIO object fails,"{'login': 'RehanSD', 'id': 17012605, 'node_id': 'MDQ6VXNlcjE3MDEyNjA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/17012605?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RehanSD', 'html_url': 'https://github.com/RehanSD', 'followers_url': 'https://api.github.com/users/RehanSD/followers', 'following_url': 'https://api.github.com/users/RehanSD/following{/other_user}', 'gists_url': 'https://api.github.com/users/RehanSD/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RehanSD/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RehanSD/subscriptions', 'organizations_url': 'https://api.github.com/users/RehanSD/orgs', 'repos_url': 'https://api.github.com/users/RehanSD/repos', 'events_url': 'https://api.github.com/users/RehanSD/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RehanSD/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-26T03:38:56Z,2022-01-26T03:38:56Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
from io import BytesIO
df = pd.DataFrame([[1, 2]])
bio = BytesIO()
df.to_csv(bio)
bio.seek(0)
pd.read_csv(bio, memory_map=True)
```


### Issue Description

The `read_csv` fails, and provides this error:
```python
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-7-c255f3bb77b8> in <module>
----> 1 pd.read_csv(bio, memory_map=True)

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312
    313         return wrapper

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers/readers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    678     kwds.update(kwds_defaults)
    679
--> 680     return _read(filepath_or_buffer, kwds)
    681
    682

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers/readers.py in _read(filepath_or_buffer, kwds)
    573
    574     # Create the parser.
--> 575     parser = TextFileReader(filepath_or_buffer, **kwds)
    576
    577     if chunksize or iterator:

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers/readers.py in __init__(self, f, engine, **kwds)
    931
    932         self.handles: IOHandles | None = None
--> 933         self._engine = self._make_engine(f, self.engine)
    934
    935     def close(self):

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers/readers.py in _make_engine(self, f, engine)
   1215             # ""Union[str, PathLike[str], ReadCsvBuffer[bytes], ReadCsvBuffer[str]]""
   1216             # , ""str"", ""bool"", ""Any"", ""Any"", ""Any"", ""Any"", ""Any""
-> 1217             self.handles = get_handle(  # type: ignore[call-overload]
   1218                 f,
   1219                 mode,

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    680
    681     # memory mapping needs to be the first step
--> 682     handle, memory_map, handles = _maybe_memory_map(
    683         handle,
    684         memory_map,

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/common.py in _maybe_memory_map(handle, memory_map, encoding, mode, errors, decode)
   1085         wrapped = cast(
   1086             BaseBuffer,
-> 1087             _MMapWrapper(handle, encoding, errors, decode),  # type: ignore[arg-type]
   1088         )
   1089     finally:

~/.miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/common.py in __init__(self, f, encoding, errors, decode)
    959                 continue
    960             self.attributes[attribute] = getattr(f, attribute)()
--> 961         self.mmap = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
    962
    963     def __getattr__(self, name: str):

UnsupportedOperation: fileno
```

It seems that the error is because `fileno` is being called on a `BytesIO` object. This code does work in pandas 1.3.4, which is odd, so I took a look at the sources to see what was different and noticed that in `_maybe_memory_map`, the `except` when trying to instant the `_MMapWrapper` was removed from [common.py](https://github.com/pandas-dev/pandas/blob/434faffddb7cbeec62080d0fdaa4310040ddbdeb/pandas/io/common.py#L1089). ([Old common.py for reference](https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/io/common.py#L918)).


### Expected Behavior

I would expect the `read_csv` to succeed and the DataFrame to be read.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.3.1
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2021.11.1
gcsfs            : None
matplotlib       : 3.2.2
numba            : None
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.16.0
pyarrow          : 3.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.11.1
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : None
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45630/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45630/timeline,
2,https://api.github.com/repos/pandas-dev/pandas/issues/45629,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45629/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45629/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45629/events,https://github.com/pandas-dev/pandas/issues/45629,1114569978,I_kwDOAA0YD85Cbvz6,45629,BUG: `set_index` with object column gives wrong stack level in warning,"{'login': 'ntjess', 'id': 23620506, 'node_id': 'MDQ6VXNlcjIzNjIwNTA2', 'avatar_url': 'https://avatars.githubusercontent.com/u/23620506?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ntjess', 'html_url': 'https://github.com/ntjess', 'followers_url': 'https://api.github.com/users/ntjess/followers', 'following_url': 'https://api.github.com/users/ntjess/following{/other_user}', 'gists_url': 'https://api.github.com/users/ntjess/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ntjess/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ntjess/subscriptions', 'organizations_url': 'https://api.github.com/users/ntjess/orgs', 'repos_url': 'https://api.github.com/users/ntjess/repos', 'events_url': 'https://api.github.com/users/ntjess/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ntjess/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-26T02:47:25Z,2022-01-26T02:47:25Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([[None,2,3], [3,4,5]], dtype=object)
df.set_index(1)
```


### Issue Description

```
...\miniconda3\envs\py39\lib\site-packages\pandas\core\indexes\base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
```

Side note -- is it possible in pandas 1.4 to `set_index` using object types without emitting this warning? I don't see an alternative recommendation or additional argument to allow this.

### Expected Behavior

The warning should show my code, not pandas code

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22000
machine          : AMD64
processor        : AMD64 Family 23 Model 104 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45629/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45629/timeline,
3,https://api.github.com/repos/pandas-dev/pandas/issues/45627,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45627/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45627/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45627/events,https://github.com/pandas-dev/pandas/pull/45627,1114477360,PR_kwDOAA0YD84xlsoW,45627,CLN: Use pytest -r to show skipped tests instead of print_skipped.py,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}]",open,False,,[],,0,2022-01-25T23:53:06Z,2022-01-26T06:34:09Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45627', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45627', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45627.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45627.patch', 'merged_at': None}",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45627/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45627/timeline,
4,https://api.github.com/repos/pandas-dev/pandas/issues/45626,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45626/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45626/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45626/events,https://github.com/pandas-dev/pandas/pull/45626,1114454050,PR_kwDOAA0YD84xlny9,45626,BUG: parse_time_string with np.str_ obj,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}]",open,False,,[],,0,2022-01-25T23:12:07Z,2022-01-26T04:26:14Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45626', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45626', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45626.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45626.patch', 'merged_at': None}","- [x] closes #45580
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45626/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45626/timeline,
5,https://api.github.com/repos/pandas-dev/pandas/issues/45625,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45625/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45625/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45625/events,https://github.com/pandas-dev/pandas/pull/45625,1114426220,PR_kwDOAA0YD84xliDh,45625,BUG: SeriesGroupBy.value_counts - index name missing in categorical columns,"{'login': 'NumberPiOso', 'id': 46936498, 'node_id': 'MDQ6VXNlcjQ2OTM2NDk4', 'avatar_url': 'https://avatars.githubusercontent.com/u/46936498?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/NumberPiOso', 'html_url': 'https://github.com/NumberPiOso', 'followers_url': 'https://api.github.com/users/NumberPiOso/followers', 'following_url': 'https://api.github.com/users/NumberPiOso/following{/other_user}', 'gists_url': 'https://api.github.com/users/NumberPiOso/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/NumberPiOso/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/NumberPiOso/subscriptions', 'organizations_url': 'https://api.github.com/users/NumberPiOso/orgs', 'repos_url': 'https://api.github.com/users/NumberPiOso/repos', 'events_url': 'https://api.github.com/users/NumberPiOso/events{/privacy}', 'received_events_url': 'https://api.github.com/users/NumberPiOso/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-25T22:29:57Z,2022-01-25T22:29:57Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45625', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45625', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45625.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45625.patch', 'merged_at': None}","- [X] closes  #44324
- [X] tests added / passed
- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [X] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45625/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45625/timeline,
6,https://api.github.com/repos/pandas-dev/pandas/issues/45623,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45623/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45623/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45623/events,https://github.com/pandas-dev/pandas/pull/45623,1114370115,PR_kwDOAA0YD84xlWJ6,45623,REGR: loc.setitem losing index name when df was empty before,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/93', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93/labels', 'id': 7593147, 'node_id': 'MI_kwDOAA0YD84Ac9y7', 'number': 93, 'title': '1.4.1', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 22, 'state': 'open', 'created_at': '2022-01-20T14:43:52Z', 'updated_at': '2022-01-26T05:12:08Z', 'due_on': '2022-02-12T08:00:00Z', 'closed_at': None}",0,2022-01-25T21:15:50Z,2022-01-26T01:35:06Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45623', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45623', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45623.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45623.patch', 'merged_at': None}","- [x] closes #45621
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45623/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45623/timeline,
7,https://api.github.com/repos/pandas-dev/pandas/issues/45622,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45622/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45622/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45622/events,https://github.com/pandas-dev/pandas/pull/45622,1114365019,PR_kwDOAA0YD84xlVEd,45622,BUG: NumericArray * td64_array,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-25T21:09:44Z,2022-01-25T22:20:31Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45622', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45622', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45622.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45622.patch', 'merged_at': None}","- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45622/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45622/timeline,
8,https://api.github.com/repos/pandas-dev/pandas/issues/45621,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45621/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45621/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45621/events,https://github.com/pandas-dev/pandas/issues/45621,1114321969,I_kwDOAA0YD85CazQx,45621,BUG: 1.4.0 does not preserve initially empty Index and appended by `loc` assignment.,"{'login': 'ketozhang', 'id': 13506487, 'node_id': 'MDQ6VXNlcjEzNTA2NDg3', 'avatar_url': 'https://avatars.githubusercontent.com/u/13506487?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ketozhang', 'html_url': 'https://github.com/ketozhang', 'followers_url': 'https://api.github.com/users/ketozhang/followers', 'following_url': 'https://api.github.com/users/ketozhang/following{/other_user}', 'gists_url': 'https://api.github.com/users/ketozhang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ketozhang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ketozhang/subscriptions', 'organizations_url': 'https://api.github.com/users/ketozhang/orgs', 'repos_url': 'https://api.github.com/users/ketozhang/repos', 'events_url': 'https://api.github.com/users/ketozhang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ketozhang/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/93', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93/labels', 'id': 7593147, 'node_id': 'MI_kwDOAA0YD84Ac9y7', 'number': 93, 'title': '1.4.1', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 22, 'state': 'open', 'created_at': '2022-01-20T14:43:52Z', 'updated_at': '2022-01-26T05:12:08Z', 'due_on': '2022-02-12T08:00:00Z', 'closed_at': None}",2,2022-01-25T20:18:10Z,2022-01-25T21:08:15Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(columns=[""a"", ""b""]).set_index(""a"")
print(df.index, id(df.index))  # Index([], dtype='object', name='a') 4644041536
df.loc[0] = {""b"": 0}
print(df.index, id(df.index))  # Int64Index([0], dtype='int64') 4726025904
```


### Issue Description

Given an empty dataframe with a index column name set, when adding a row on a specific index using `df.loc[INDEX]`, the original index is not preserved. Furthermore, what gets returned is not type`Index` but is `Int64Index` when the passed in index is an integer.

### Expected Behavior

The modified index should print out `Index([0], dtype='int64', name='a')`.

### Installed Versions

1.4.0","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45621/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45621/timeline,
9,https://api.github.com/repos/pandas-dev/pandas/issues/45618,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45618/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45618/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45618/events,https://github.com/pandas-dev/pandas/issues/45618,1113999499,I_kwDOAA0YD85CZkiL,45618,BUG: passing a SparseArray to pd.Index - overly eager FutureWarning,"{'login': 'jsignell', 'id': 4806877, 'node_id': 'MDQ6VXNlcjQ4MDY4Nzc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4806877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jsignell', 'html_url': 'https://github.com/jsignell', 'followers_url': 'https://api.github.com/users/jsignell/followers', 'following_url': 'https://api.github.com/users/jsignell/following{/other_user}', 'gists_url': 'https://api.github.com/users/jsignell/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jsignell/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jsignell/subscriptions', 'organizations_url': 'https://api.github.com/users/jsignell/orgs', 'repos_url': 'https://api.github.com/users/jsignell/repos', 'events_url': 'https://api.github.com/users/jsignell/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jsignell/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 49182326, 'node_id': 'MDU6TGFiZWw0OTE4MjMyNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Sparse', 'name': 'Sparse', 'color': '009800', 'default': False, 'description': 'Sparse Data Type'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/93', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/93/labels', 'id': 7593147, 'node_id': 'MI_kwDOAA0YD84Ac9y7', 'number': 93, 'title': '1.4.1', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 22, 'state': 'open', 'created_at': '2022-01-20T14:43:52Z', 'updated_at': '2022-01-26T05:12:08Z', 'due_on': '2022-02-12T08:00:00Z', 'closed_at': None}",1,2022-01-25T15:02:39Z,2022-01-25T20:50:14Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
In [1]: import pandas as pd
   ...: 
   ...: s = pd.Series(pd.Categorical([""a"", ""b"", ""a""], categories=[""a"", ""b"", ""c""]))
   ...: exp = pd.get_dummies(s, sparse=True)
   ...: exp.sort_values(by=exp.columns.tolist())
<ipython-input-1-312167088340>:5: FutureWarning: In a future version, passing a SparseArray to pd.Index will store that array directly instead of converting to a dense numpy ndarray. To retain the old behavior, use pd.Index(arr.to_numpy()) instead
  exp.sort_values(by=exp.columns.tolist())
<ipython-input-1-312167088340>:5: FutureWarning: In a future version, passing a SparseArray to pd.Index will store that array directly instead of converting to a dense numpy ndarray. To retain the old behavior, use pd.Index(arr.to_numpy()) instead
  exp.sort_values(by=exp.columns.tolist())
<ipython-input-1-312167088340>:5: FutureWarning: In a future version, passing a SparseArray to pd.Index will store that array directly instead of converting to a dense numpy ndarray. To retain the old behavior, use pd.Index(arr.to_numpy()) instead
  exp.sort_values(by=exp.columns.tolist())
Out[1]: 
   a  b  c
1  0  1  0
0  1  0  0
2  1  0  0
```


### Issue Description

In pandas 1.4.0 there is a FutureWarning that I believe is too aggressive. In the example above it is not clear what to change in the code snippet. For context this came up in the dask test suite. 

### Expected Behavior

I imagine there might be some internal code that is coercing the array that I provided into an index. It this is the expected behavior then I think the error message needs to be changed to make it clear how to fix the code snippet.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-7633-generic
Version          : #35~1630100930~20.04~ae2753e-Ubuntu SMP Mon Aug 30 18:23:52 UTC 
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.8.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.7.2
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.0
numexpr          : 2.8.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.01.0
scipy            : 1.7.3
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : 0.20.2
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45618/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45618/timeline,
10,https://api.github.com/repos/pandas-dev/pandas/issues/45617,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45617/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45617/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45617/events,https://github.com/pandas-dev/pandas/issues/45617,1113975182,I_kwDOAA0YD85CZemO,45617,"BUG: describe does not generate unique values for numbers, inconsistent with nunique","{'login': 'Archer6621', 'id': 6449766, 'node_id': 'MDQ6VXNlcjY0NDk3NjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6449766?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Archer6621', 'html_url': 'https://github.com/Archer6621', 'followers_url': 'https://api.github.com/users/Archer6621/followers', 'following_url': 'https://api.github.com/users/Archer6621/following{/other_user}', 'gists_url': 'https://api.github.com/users/Archer6621/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Archer6621/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Archer6621/subscriptions', 'organizations_url': 'https://api.github.com/users/Archer6621/orgs', 'repos_url': 'https://api.github.com/users/Archer6621/repos', 'events_url': 'https://api.github.com/users/Archer6621/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Archer6621/received_events', 'type': 'User', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}]",open,False,,[],,2,2022-01-25T14:43:05Z,2022-01-25T21:02:16Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    {
        ""A"": [1, 2, 2],
        ""B"": [1.3, 1.3, 1.3],
        ""C"": ['a', 'b', 'c']
    }
)

print(df.describe(include='all'))
print()
print(""nunique for A:"", df.A.nunique())
print(""nunique for B:"", df.B.nunique())
```


### Issue Description

Currently the unique statistic for number series shows up as `NaN` in `DataFrame.describe`, even though calling `nunique` on such a series does produce a number (that can be useful for e.g. identifying fully unique series in a standard way for all series, especially with an integer type).

Output of the above example:
```
               A    B    C
count   3.000000  3.0    3
unique       NaN  NaN    3
top          NaN  NaN    a
freq         NaN  NaN    1
mean    1.666667  1.3  NaN
std     0.577350  0.0  NaN
min     1.000000  1.3  NaN
25%     1.500000  1.3  NaN
50%     2.000000  1.3  NaN
75%     2.000000  1.3  NaN
max     2.000000  1.3  NaN

nunique for A: 2
nunique for B: 1
```

### Expected Behavior

I would expect the `unique` field in `DataFrame.describe` for number series to work the same way as `nunique` being called directly on a number series, but now it just shows `NaN`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-9-amd64
Version          : #1 SMP Debian 5.10.70-1 (2021-09-30)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : 2021.08.1
gcsfs            : None
matplotlib       : 3.4.3
numba            : 0.54.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45617/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45617/timeline,
11,https://api.github.com/repos/pandas-dev/pandas/issues/45616,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45616/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45616/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45616/events,https://github.com/pandas-dev/pandas/pull/45616,1113936359,PR_kwDOAA0YD84xj65k,45616,BUG: is_bool_dtype raises AttributeError when checking categorical Series,"{'login': 'Robbie-Palmer', 'id': 8760191, 'node_id': 'MDQ6VXNlcjg3NjAxOTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8760191?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Robbie-Palmer', 'html_url': 'https://github.com/Robbie-Palmer', 'followers_url': 'https://api.github.com/users/Robbie-Palmer/followers', 'following_url': 'https://api.github.com/users/Robbie-Palmer/following{/other_user}', 'gists_url': 'https://api.github.com/users/Robbie-Palmer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Robbie-Palmer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Robbie-Palmer/subscriptions', 'organizations_url': 'https://api.github.com/users/Robbie-Palmer/orgs', 'repos_url': 'https://api.github.com/users/Robbie-Palmer/repos', 'events_url': 'https://api.github.com/users/Robbie-Palmer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Robbie-Palmer/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-25T14:11:30Z,2022-01-25T14:11:30Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45616', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45616', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45616.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45616.patch', 'merged_at': None}","- [X] closes #45615
- [X] tests added / passed
- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [X] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45616/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45616/timeline,
12,https://api.github.com/repos/pandas-dev/pandas/issues/45615,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45615/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45615/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45615/events,https://github.com/pandas-dev/pandas/issues/45615,1113663588,I_kwDOAA0YD85CYShk,45615,BUG: is_bool_dtype 'Series' object has no attribute 'categories',"{'login': 'Robbie-Palmer', 'id': 8760191, 'node_id': 'MDQ6VXNlcjg3NjAxOTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8760191?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Robbie-Palmer', 'html_url': 'https://github.com/Robbie-Palmer', 'followers_url': 'https://api.github.com/users/Robbie-Palmer/followers', 'following_url': 'https://api.github.com/users/Robbie-Palmer/following{/other_user}', 'gists_url': 'https://api.github.com/users/Robbie-Palmer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Robbie-Palmer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Robbie-Palmer/subscriptions', 'organizations_url': 'https://api.github.com/users/Robbie-Palmer/orgs', 'repos_url': 'https://api.github.com/users/Robbie-Palmer/repos', 'events_url': 'https://api.github.com/users/Robbie-Palmer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Robbie-Palmer/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,"{'login': 'Robbie-Palmer', 'id': 8760191, 'node_id': 'MDQ6VXNlcjg3NjAxOTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8760191?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Robbie-Palmer', 'html_url': 'https://github.com/Robbie-Palmer', 'followers_url': 'https://api.github.com/users/Robbie-Palmer/followers', 'following_url': 'https://api.github.com/users/Robbie-Palmer/following{/other_user}', 'gists_url': 'https://api.github.com/users/Robbie-Palmer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Robbie-Palmer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Robbie-Palmer/subscriptions', 'organizations_url': 'https://api.github.com/users/Robbie-Palmer/orgs', 'repos_url': 'https://api.github.com/users/Robbie-Palmer/repos', 'events_url': 'https://api.github.com/users/Robbie-Palmer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Robbie-Palmer/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'Robbie-Palmer', 'id': 8760191, 'node_id': 'MDQ6VXNlcjg3NjAxOTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8760191?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Robbie-Palmer', 'html_url': 'https://github.com/Robbie-Palmer', 'followers_url': 'https://api.github.com/users/Robbie-Palmer/followers', 'following_url': 'https://api.github.com/users/Robbie-Palmer/following{/other_user}', 'gists_url': 'https://api.github.com/users/Robbie-Palmer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Robbie-Palmer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Robbie-Palmer/subscriptions', 'organizations_url': 'https://api.github.com/users/Robbie-Palmer/orgs', 'repos_url': 'https://api.github.com/users/Robbie-Palmer/repos', 'events_url': 'https://api.github.com/users/Robbie-Palmer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Robbie-Palmer/received_events', 'type': 'User', 'site_admin': False}]",,1,2022-01-25T09:51:55Z,2022-01-25T12:33:12Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
from pandas import Series
from pandas.core.dtypes.common import is_bool_dtype

s = Series(['foo', 'bar', 'baz'], dtype='category')
is_bool_dtype(s)
```


### Issue Description

In pandas v1.3.0 the `is_bool_dtype` function returns `False` when passed a categorical `Series`
In pandas v1.4.0 it raises the error :
```
Traceback (most recent call last):
  File ""./pandas/core/dtypes/common.py"", line 1322, in is_bool_dtype
    arr_or_dtype = arr_or_dtype.categories
  File ""./pandas/core/generic.py"", line 5583, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'categories'
```

### Expected Behavior

Expect `is_bool_dtype` to return `False` for categorical Series as happened in previous pandas versions

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-96-generic
Version          : #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8
pandas           : 1.4.0
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.2.4
setuptools       : 59.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 5.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45615/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45615/timeline,
13,https://api.github.com/repos/pandas-dev/pandas/issues/45614,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45614/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45614/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45614/events,https://github.com/pandas-dev/pandas/issues/45614,1113565184,I_kwDOAA0YD85CX6gA,45614, ENH: In-built functions/API or utility to handle avro files,"{'login': 'KayvanShah1', 'id': 59110083, 'node_id': 'MDQ6VXNlcjU5MTEwMDgz', 'avatar_url': 'https://avatars.githubusercontent.com/u/59110083?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/KayvanShah1', 'html_url': 'https://github.com/KayvanShah1', 'followers_url': 'https://api.github.com/users/KayvanShah1/followers', 'following_url': 'https://api.github.com/users/KayvanShah1/following{/other_user}', 'gists_url': 'https://api.github.com/users/KayvanShah1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/KayvanShah1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/KayvanShah1/subscriptions', 'organizations_url': 'https://api.github.com/users/KayvanShah1/orgs', 'repos_url': 'https://api.github.com/users/KayvanShah1/repos', 'events_url': 'https://api.github.com/users/KayvanShah1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/KayvanShah1/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-01-25T08:20:43Z,2022-01-25T12:11:12Z,,NONE,,,,"#### Is your feature request related to a problem?

It would be great if pandas has inbuilt capabilities to handle - read, write, update, manipulate `Avro` files

#### Describe the solution you'd like

`read_avro()` and `to_avro()` functions

#### Describe alternatives you've considered

There are two installable libraries for working with Avro files:
[avro](https://avro.apache.org/) & [fastavro](https://fastavro.readthedocs.io/en/latest/)

#### Additional context
- https://towardsdatascience.com/csv-files-for-storage-absolutely-not-use-apache-avro-instead-7b7296149326

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45614/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45614/timeline,
14,https://api.github.com/repos/pandas-dev/pandas/issues/45612,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45612/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45612/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45612/events,https://github.com/pandas-dev/pandas/pull/45612,1113413501,PR_kwDOAA0YD84xiPRc,45612,DOC: Improve reshaping.rst,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],,0,2022-01-25T04:29:53Z,2022-01-26T05:13:13Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45612', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45612', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45612.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45612.patch', 'merged_at': None}","* Add more sphinx references
* Links function docs back to `reshaping.rst`
* Convert `code-block` to `ipython`
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45612/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45612/timeline,
15,https://api.github.com/repos/pandas-dev/pandas/issues/45611,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45611/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45611/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45611/events,https://github.com/pandas-dev/pandas/pull/45611,1113384543,PR_kwDOAA0YD84xiJSx,45611,CI: use pipx and build to simplify and remove a workaround (2),"{'login': 'henryiii', 'id': 4616906, 'node_id': 'MDQ6VXNlcjQ2MTY5MDY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4616906?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/henryiii', 'html_url': 'https://github.com/henryiii', 'followers_url': 'https://api.github.com/users/henryiii/followers', 'following_url': 'https://api.github.com/users/henryiii/following{/other_user}', 'gists_url': 'https://api.github.com/users/henryiii/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/henryiii/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/henryiii/subscriptions', 'organizations_url': 'https://api.github.com/users/henryiii/orgs', 'repos_url': 'https://api.github.com/users/henryiii/repos', 'events_url': 'https://api.github.com/users/henryiii/events{/privacy}', 'received_events_url': 'https://api.github.com/users/henryiii/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-25T03:33:14Z,2022-01-25T03:56:21Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45611', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45611', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45611.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45611.patch', 'merged_at': None}","- CI: use pipx and build to simplify and remove a workaround
- ci: drop setup-python, show build version

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

This cleans up the SDist build slightly. First, it uses PyPA's ""build"" instead of directly calling `setup.py`, which will respect PEP 518 requirements and avoids the workaround of installing NumPy to be able to run setup.py. It also uses pipx to avoid needless setup; PyPA's pipx is provides as a first-class package manager on GitHub Actions (and Azure, they share images).

Repushing #43157. No changes (except rebasing). I think the next step was to make sure the local SDist builds were brought in sync with this.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45611/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45611/timeline,
16,https://api.github.com/repos/pandas-dev/pandas/issues/45610,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45610/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45610/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45610/events,https://github.com/pandas-dev/pandas/pull/45610,1113354128,PR_kwDOAA0YD84xiDE6,45610,TYP: return type of read_csv/table,"{'login': 'twoertwein', 'id': 6618166, 'node_id': 'MDQ6VXNlcjY2MTgxNjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/twoertwein', 'html_url': 'https://github.com/twoertwein', 'followers_url': 'https://api.github.com/users/twoertwein/followers', 'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}', 'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions', 'organizations_url': 'https://api.github.com/users/twoertwein/orgs', 'repos_url': 'https://api.github.com/users/twoertwein/repos', 'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}', 'received_events_url': 'https://api.github.com/users/twoertwein/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],,1,2022-01-25T02:34:26Z,2022-01-25T20:56:32Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45610', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45610', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45610.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45610.patch', 'merged_at': None}","Return type of read_csv/table (union for now, overload can be used when positional keywords are deprecated), type TextFileReader, and type some random arguments of read_csv/table","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45610/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45610/timeline,
17,https://api.github.com/repos/pandas-dev/pandas/issues/45609,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45609/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45609/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45609/events,https://github.com/pandas-dev/pandas/pull/45609,1113351808,PR_kwDOAA0YD84xiCnW,45609,Diff low precision ints,"{'login': 'lukemanley', 'id': 8519523, 'node_id': 'MDQ6VXNlcjg1MTk1MjM=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8519523?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lukemanley', 'html_url': 'https://github.com/lukemanley', 'followers_url': 'https://api.github.com/users/lukemanley/followers', 'following_url': 'https://api.github.com/users/lukemanley/following{/other_user}', 'gists_url': 'https://api.github.com/users/lukemanley/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lukemanley/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lukemanley/subscriptions', 'organizations_url': 'https://api.github.com/users/lukemanley/orgs', 'repos_url': 'https://api.github.com/users/lukemanley/repos', 'events_url': 'https://api.github.com/users/lukemanley/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lukemanley/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-25T02:29:30Z,2022-01-25T02:29:30Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45609', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45609', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45609.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45609.patch', 'merged_at': None}","- [x] closes #45562
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry


Submitting this PR as a potential option. This changes the diff method to upcast int8/int16 to float64 similar to shift and other methods. It avoids the int8/int16 > float64 cython issue referenced in the code by doing an initial cast from int8/int16 > int32. Note the tests were updated to now expect float64 in a few cases. 

If the existing behavior is preferred, I'm happy to close this. I thought the consistency and fewer special cases elsewhere might be worth the change here. ","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45609/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45609/timeline,
18,https://api.github.com/repos/pandas-dev/pandas/issues/45608,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45608/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45608/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45608/events,https://github.com/pandas-dev/pandas/issues/45608,1113341729,I_kwDOAA0YD85CXD8h,45608,BUG: cannot construct Index of empty tuples,"{'login': 'batterseapower', 'id': 18488, 'node_id': 'MDQ6VXNlcjE4NDg4', 'avatar_url': 'https://avatars.githubusercontent.com/u/18488?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/batterseapower', 'html_url': 'https://github.com/batterseapower', 'followers_url': 'https://api.github.com/users/batterseapower/followers', 'following_url': 'https://api.github.com/users/batterseapower/following{/other_user}', 'gists_url': 'https://api.github.com/users/batterseapower/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/batterseapower/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/batterseapower/subscriptions', 'organizations_url': 'https://api.github.com/users/batterseapower/orgs', 'repos_url': 'https://api.github.com/users/batterseapower/repos', 'events_url': 'https://api.github.com/users/batterseapower/events{/privacy}', 'received_events_url': 'https://api.github.com/users/batterseapower/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-25T02:11:07Z,2022-01-25T02:11:07Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
pd.Index([()]) # Fails, the MultiIndex constructor complains that you ""must pass non-zero number of levels/codes""
pd.Index([(), None])[:1] # Works
```


### Issue Description

The index constructor has a special case for when the input list consists purely of tuples. However, it's not aware of the special case in MultiIndex that forbids number of levels == 0. Index should avoid trying to construct a MultiIndex in this case.

(Even better, MultiIndex could just support 0-level indexes. Yes, they are trivial in some sense, but they are also perfectly sensible.)

### Expected Behavior

Both lines should evaluate correctly to identical indexes.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.1
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : None
numba            : 0.53.1
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45608/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45608/timeline,
19,https://api.github.com/repos/pandas-dev/pandas/issues/45607,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45607/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45607/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45607/events,https://github.com/pandas-dev/pandas/issues/45607,1113339795,I_kwDOAA0YD85CXDeT,45607,QST: Why does pandas.GroupBy.apply() ignore the sort flag in some situations?,"{'login': 'normanius', 'id': 11406002, 'node_id': 'MDQ6VXNlcjExNDA2MDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/11406002?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/normanius', 'html_url': 'https://github.com/normanius', 'followers_url': 'https://api.github.com/users/normanius/followers', 'following_url': 'https://api.github.com/users/normanius/following{/other_user}', 'gists_url': 'https://api.github.com/users/normanius/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/normanius/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/normanius/subscriptions', 'organizations_url': 'https://api.github.com/users/normanius/orgs', 'repos_url': 'https://api.github.com/users/normanius/repos', 'events_url': 'https://api.github.com/users/normanius/events{/privacy}', 'received_events_url': 'https://api.github.com/users/normanius/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform'}]",open,False,,[],,1,2022-01-25T02:07:41Z,2022-01-25T23:14:49Z,,NONE,,,,"### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).


### Link to question on StackOverflow

https://stackoverflow.com/questions/70842600/

### Question about pandas

Sample code is provided in the SO post. 

I can reproduce this problem with pandas 1.2.4 and 1.4.0.

In my opinion, this is either a design flaw or should be documented with more clarity. Other opinions?","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45607/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45607/timeline,
20,https://api.github.com/repos/pandas-dev/pandas/issues/45605,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45605/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45605/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45605/events,https://github.com/pandas-dev/pandas/issues/45605,1113229913,I_kwDOAA0YD85CWopZ,45605,TST: fastparquet tests failing with Python 3.10,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODUxMTQ0MTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Parquet', 'name': 'IO Parquet', 'color': '5319e7', 'default': False, 'description': 'parquet, feather'}, {'id': 2955636717, 'node_id': 'MDU6TGFiZWwyOTU1NjM2NzE3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Python%203.10', 'name': 'Python 3.10', 'color': 'fef2c0', 'default': False, 'description': ''}]",open,False,,[],,0,2022-01-24T22:57:40Z,2022-01-24T22:57:40Z,,MEMBER,,,,"Example build: https://github.com/pandas-dev/pandas/runs/4916890560?check_suite_focus=true

Generally failing with

```
    def _parse_header(self, f, verify=True):
        if self.fn and self.fn.endswith(""_metadata""):
            #  no point attempting to read footer only for pure metadata
            data = f.read()[4:-8]
            self._head_size = len(data)
        else:
            try:
                f.seek(0)
                if verify:
                    assert f.read(4) == b'PAR1'
                f.seek(-8, 2)
                head_size = struct.unpack('<i', f.read(4))[0]
                if verify:
                    assert f.read() == b'PAR1'
                self._head_size = head_size
                f.seek(-(head_size + 8), 2)
                data = f.read(head_size)
            except (AssertionError, struct.error):
                raise ParquetException('File parse failed: %s' % self.fn)
    
        f = io.BytesIO(data)
        try:
            fmd = read_thrift(f, parquet_thrift.FileMetaData)
        except Exception:
>           raise ParquetException('Metadata parse failed: %s' % self.fn)
E           fastparquet.util.ParquetException: Metadata parse failed: None

/usr/share/miniconda/envs/pandas-dev/lib/python3.10/site-packages/fastparquet/api.py:189: ParquetException
_ test_server_and_custom_headers[ParquetFastParquetUserAgentResponder-read_parquet-fastparquet] _
[gw0] linux -- Python 3.10.2 /usr/share/miniconda/envs/pandas-dev/bin/python

self = <[AttributeError(""'ParquetFile' object has no attribute '_schema'"") raised in repr()] ParquetFile object at 0x7f8ce8750eb0>
f = <_io.BytesIO object at 0x7f8ce8723bf0>, verify = False

    def _parse_header(self, f, verify=True):
        if self.fn and self.fn.endswith(""_metadata""):
            #  no point attempting to read footer only for pure metadata
            data = f.read()[4:-8]
            self._head_size = len(data)
        else:
            try:
                f.seek(0)
                if verify:
                    assert f.read(4) == b'PAR1'
                f.seek(-8, 2)
                head_size = struct.unpack('<i', f.read(4))[0]
                if verify:
                    assert f.read() == b'PAR1'
                self._head_size = head_size
                f.seek(-(head_size + 8), 2)
                data = f.read(head_size)
            except (AssertionError, struct.error):
                raise ParquetException('File parse failed: %s' % self.fn)
    
        f = io.BytesIO(data)
        try:
>           fmd = read_thrift(f, parquet_thrift.FileMetaData)

/usr/share/miniconda/envs/pandas-dev/lib/python3.10/site-packages/fastparquet/api.py:187: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_obj = <_io.BytesIO object at 0x7f8ce8723bf0>
ttype = <class 'fastparquet.parquet_thrift.parquet.ttypes.FileMetaData'>

    def read_thrift(file_obj, ttype):
        """"""Read a thrift structure from the given fo.""""""
        from thrift.transport.TTransport import TFileObjectTransport, TBufferedTransport
        starting_pos = file_obj.tell()
    
        # set up the protocol chain
        ft = TFileObjectTransport(file_obj)
        bufsize = 2 ** 16
        # for accelerated reading ensure that we wrap this so that the CReadable transport can be used.
        bt = TBufferedTransport(ft, bufsize)
        pin = TCompactProtocol(bt)
    
        # read out type
        obj = ttype()
>       obj.read(pin)

/usr/share/miniconda/envs/pandas-dev/lib/python3.10/site-packages/fastparquet/thrift_structures.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <class 'fastparquet.parquet_thrift.parquet.ttypes.FileMetaData'>
column_orders: None
created_by: None
encryption_algor...
footer_signing_key_metadata: None
key_value_metadata: None
num_rows: None
row_groups: None
schema: None
version: None

iprot = <thrift.protocol.TCompactProtocol.TCompactProtocolAccelerated object at 0x7f8ce8750a00>

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
>           iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
E           SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

/usr/share/miniconda/envs/pandas-dev/lib/python3.10/site-packages/fastparquet/parquet_thrift/parquet/ttypes.py:4446: SystemError

```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45605/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45605/timeline,
21,https://api.github.com/repos/pandas-dev/pandas/issues/45603,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45603/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45603/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45603/events,https://github.com/pandas-dev/pandas/issues/45603,1113203100,I_kwDOAA0YD85CWiGc,45603,BUG: fillna downcast object to int even downcast=False/None,"{'login': 'yinweisu', 'id': 21029745, 'node_id': 'MDQ6VXNlcjIxMDI5NzQ1', 'avatar_url': 'https://avatars.githubusercontent.com/u/21029745?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yinweisu', 'html_url': 'https://github.com/yinweisu', 'followers_url': 'https://api.github.com/users/yinweisu/followers', 'following_url': 'https://api.github.com/users/yinweisu/following{/other_user}', 'gists_url': 'https://api.github.com/users/yinweisu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yinweisu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yinweisu/subscriptions', 'organizations_url': 'https://api.github.com/users/yinweisu/orgs', 'repos_url': 'https://api.github.com/users/yinweisu/repos', 'events_url': 'https://api.github.com/users/yinweisu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yinweisu/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}]",open,False,,[],,5,2022-01-24T22:20:46Z,2022-01-25T22:17:31Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.Series([1,2,3], dtype='object')
df.fillna('', downcast=False)  # will get int64 instead
```


### Issue Description

fillna will convert an object dataframe to int64 dataframe even when downcast is specified to be False or None

### Expected Behavior

The dataframe should keep the original dtype

### Installed Versions

<details>

NSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45603/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45603/timeline,
22,https://api.github.com/repos/pandas-dev/pandas/issues/45602,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45602/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45602/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45602/events,https://github.com/pandas-dev/pandas/pull/45602,1113184901,PR_kwDOAA0YD84xhgFj,45602,QDataFrame,"{'login': 'wkerzendorf', 'id': 506116, 'node_id': 'MDQ6VXNlcjUwNjExNg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/506116?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wkerzendorf', 'html_url': 'https://github.com/wkerzendorf', 'followers_url': 'https://api.github.com/users/wkerzendorf/followers', 'following_url': 'https://api.github.com/users/wkerzendorf/following{/other_user}', 'gists_url': 'https://api.github.com/users/wkerzendorf/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wkerzendorf/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wkerzendorf/subscriptions', 'organizations_url': 'https://api.github.com/users/wkerzendorf/orgs', 'repos_url': 'https://api.github.com/users/wkerzendorf/repos', 'events_url': 'https://api.github.com/users/wkerzendorf/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wkerzendorf/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,5,2022-01-24T22:00:37Z,2022-01-25T18:23:56Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45602', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45602', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45602.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45602.patch', 'merged_at': None}","Not sure where that fits inside pandas. Happy to add tests to this but this works AFAICT. 

- [x] closes #10349
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45602/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45602/timeline,
23,https://api.github.com/repos/pandas-dev/pandas/issues/45601,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45601/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45601/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45601/events,https://github.com/pandas-dev/pandas/issues/45601,1113178975,I_kwDOAA0YD85CWcNf,45601,BUG: Replacing `pd.NA` by `None` has no effect,"{'login': 'treiher', 'id': 15232394, 'node_id': 'MDQ6VXNlcjE1MjMyMzk0', 'avatar_url': 'https://avatars.githubusercontent.com/u/15232394?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/treiher', 'html_url': 'https://github.com/treiher', 'followers_url': 'https://api.github.com/users/treiher/followers', 'following_url': 'https://api.github.com/users/treiher/following{/other_user}', 'gists_url': 'https://api.github.com/users/treiher/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/treiher/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/treiher/subscriptions', 'organizations_url': 'https://api.github.com/users/treiher/orgs', 'repos_url': 'https://api.github.com/users/treiher/repos', 'events_url': 'https://api.github.com/users/treiher/events{/privacy}', 'received_events_url': 'https://api.github.com/users/treiher/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-24T21:52:20Z,2022-01-24T21:52:20Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({""value"": [42, None]}).astype({""value"": ""Int64""})

assert df.replace({pd.NA: None}).to_dict() == {""value"": {0: 42, 1: None}}
```


### Issue Description

Since version 1.4.0 `.replace({pd.NA: None})` has no effect, `pd.NA` is not be replaced by `None` anymore.

### Expected Behavior

The assertion in the example shown above is fulfilled in version 1.3.5.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.10.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.13-arch1-1
Version          : #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.29
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45601/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45601/timeline,
24,https://api.github.com/repos/pandas-dev/pandas/issues/45598,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45598/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45598/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45598/events,https://github.com/pandas-dev/pandas/issues/45598,1113028004,I_kwDOAA0YD85CV3Wk,45598,BUG: Error in read_excel() function with some ods files,"{'login': 'f4kt', 'id': 29780020, 'node_id': 'MDQ6VXNlcjI5NzgwMDIw', 'avatar_url': 'https://avatars.githubusercontent.com/u/29780020?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/f4kt', 'html_url': 'https://github.com/f4kt', 'followers_url': 'https://api.github.com/users/f4kt/followers', 'following_url': 'https://api.github.com/users/f4kt/following{/other_user}', 'gists_url': 'https://api.github.com/users/f4kt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/f4kt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/f4kt/subscriptions', 'organizations_url': 'https://api.github.com/users/f4kt/orgs', 'repos_url': 'https://api.github.com/users/f4kt/repos', 'events_url': 'https://api.github.com/users/f4kt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/f4kt/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-24T19:03:26Z,2022-01-24T19:03:26Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

pd.read_excel('exported_with_qgis.ods')
```


### Issue Description

When taking an ods file generated from qgis (exporting a vector layer in ods format), its content.xml (internal file from ods) has newlines between XML elements, like this:
```
<table:table-row>
<table:table-cell office:value-type=""string"">
<text:p>CODIGO</text:p>
</table:table-cell>
...

```
instead of being like this:
```
<table:table-row><table:table-cell office:value-type=""string""><text:p>CODIGO</text:p></table:table-cell>
...
```
then if I open with LibreOffice calc that file it's ok, but when doing:
```
pd.read_excel(ods_file)
```
then there is this traceback:
```
AttributeError: 'Text' object has no attribute 'qname'
```
Solution:
rewrite line no. 103 of https://github.com/pandas-dev/pandas/blob/main/pandas/io/excel/_odfreader.py
```
-sheet_cells = [x for x in sheet_row.childNodes if x.qname in cell_names]
+sheet_cells = [x for x in sheet_row.childNodes if 'qname' in dir(x) and x.qname in cell_names]
```


### Expected Behavior

The expected behaviour is to ignore the newlines. LibreOffice calc opens correctly that kind of ods

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-22-generic
Version          : #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : es_ES.UTF-8
LOCALE           : es_ES.UTF-8

pandas           : 1.3.3
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.4
setuptools       : 52.0.0
Cython           : None
pytest           : 6.0.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 3.0.0
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.3.22
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.2.0
numba            : 0.54.1

```
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45598/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45598/timeline,
25,https://api.github.com/repos/pandas-dev/pandas/issues/45596,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45596/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45596/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45596/events,https://github.com/pandas-dev/pandas/pull/45596,1112973421,PR_kwDOAA0YD84xgzk_,45596,REF: share IntegerArray/FloatingArray coerce_to_array,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-01-24T18:05:34Z,2022-01-24T21:49:52Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45596', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45596', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45596.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45596.patch', 'merged_at': None}","- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45596/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45596/timeline,
26,https://api.github.com/repos/pandas-dev/pandas/issues/45595,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45595/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45595/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45595/events,https://github.com/pandas-dev/pandas/issues/45595,1112936145,I_kwDOAA0YD85CVg7R,45595,BUG : Can't create datetime ranges with offset objects as freq.,"{'login': 'aulemahal', 'id': 20629530, 'node_id': 'MDQ6VXNlcjIwNjI5NTMw', 'avatar_url': 'https://avatars.githubusercontent.com/u/20629530?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/aulemahal', 'html_url': 'https://github.com/aulemahal', 'followers_url': 'https://api.github.com/users/aulemahal/followers', 'following_url': 'https://api.github.com/users/aulemahal/following{/other_user}', 'gists_url': 'https://api.github.com/users/aulemahal/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/aulemahal/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/aulemahal/subscriptions', 'organizations_url': 'https://api.github.com/users/aulemahal/orgs', 'repos_url': 'https://api.github.com/users/aulemahal/repos', 'events_url': 'https://api.github.com/users/aulemahal/events{/privacy}', 'received_events_url': 'https://api.github.com/users/aulemahal/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-24T17:26:18Z,2022-01-24T17:36:15Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

dr = pd.date_range('2001-01-01', freq=pd.DateOffset(days=1), periods=731)
dr.get_slice_bound('2001', side='left')
```


### Issue Description

Since pandas 1.4.0, this fails with `NotImplementedError: Prefix not defined`, full traceback below.

<details>

```python3
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-40-cfbcb228c06d> in <module>
----> 1 dr.get_slice_bound('2001', side='left')

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py in get_slice_bound(self, label, side, kind)
    776         if isinstance(label, date) and not isinstance(label, datetime):
    777             label = Timestamp(label).to_pydatetime()
--> 778         return super().get_slice_bound(label, side=side, kind=kind)
    779 
    780     # --------------------------------------------------------------------

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_slice_bound(self, label, side, kind)
   6391         # For datetime indices label may be a string that has to be converted
   6392         # to datetime boundary according to its resolution.
-> 6393         label = self._maybe_cast_slice_bound(label, side)
   6394 
   6395         # we need to look up the label

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py in _maybe_cast_slice_bound(self, label, side, kind)
    692     @doc(DatetimeTimedeltaMixin._maybe_cast_slice_bound)
    693     def _maybe_cast_slice_bound(self, label, side: str, kind=lib.no_default):
--> 694         label = super()._maybe_cast_slice_bound(label, side, kind=kind)
    695         self._deprecate_mismatched_indexing(label)
    696         return self._maybe_cast_for_get_loc(label)

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py in _maybe_cast_slice_bound(self, label, side, kind)
    308         if isinstance(label, str):
    309             try:
--> 310                 parsed, reso = self._parse_with_reso(label)
    311             except ValueError as err:
    312                 # DTI -> parsing.DateParseError

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py in _parse_with_reso(self, label)
    229     def _parse_with_reso(self, label: str):
    230         # overridden by TimedeltaIndex
--> 231         parsed, reso_str = parsing.parse_time_string(label, self.freq)
    232         reso = Resolution.from_attrname(reso_str)
    233         return parsed, reso

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/_libs/tslibs/parsing.pyx in pandas._libs.tslibs.parsing.parse_time_string()

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/_libs/tslibs/offsets.pyx in pandas._libs.tslibs.offsets.BaseOffset.rule_code.__get__()

/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/pandas/_libs/tslibs/offsets.pyx in pandas._libs.tslibs.offsets.BaseOffset._prefix.__get__()

NotImplementedError: Prefix not defined
```

</details>

This issue was raised in my code when using xarray and slicing on a time coordinate which was generated with the provided code. There might be other ways to trigger an error, but it seems that since 1.4.0, passing a `DateOffset` to `date_range` is broken. The documentation still allows `DateOffset` objects (if says : `freq : str or DateOffset, default 'D'`).

### Expected Behavior

If I use, `freq='D'`, the code behaves as it did before and, in this case, returns `0`.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.16.0-arch1-1
Version          : #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : fr_CA.utf8
LOCALE           : fr_CA.UTF-8

pandas           : 1.4.0
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 57.4.0
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : 2021.07.0
gcsfs            : None
matplotlib       : 3.4.3
numba            : 0.54.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.20.2
xlrd             : 1.2.0
xlwt             : 1.3.0
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45595/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45595/timeline,
27,https://api.github.com/repos/pandas-dev/pandas/issues/45594,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45594/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45594/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45594/events,https://github.com/pandas-dev/pandas/pull/45594,1112917296,PR_kwDOAA0YD84xgn3U,45594,Add typing tests according to the issue 45252,"{'login': 'zkrolikowski-vl', 'id': 63653095, 'node_id': 'MDQ6VXNlcjYzNjUzMDk1', 'avatar_url': 'https://avatars.githubusercontent.com/u/63653095?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zkrolikowski-vl', 'html_url': 'https://github.com/zkrolikowski-vl', 'followers_url': 'https://api.github.com/users/zkrolikowski-vl/followers', 'following_url': 'https://api.github.com/users/zkrolikowski-vl/following{/other_user}', 'gists_url': 'https://api.github.com/users/zkrolikowski-vl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zkrolikowski-vl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zkrolikowski-vl/subscriptions', 'organizations_url': 'https://api.github.com/users/zkrolikowski-vl/orgs', 'repos_url': 'https://api.github.com/users/zkrolikowski-vl/repos', 'events_url': 'https://api.github.com/users/zkrolikowski-vl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zkrolikowski-vl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],,4,2022-01-24T17:09:16Z,2022-01-25T21:40:24Z,,CONTRIBUTOR,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/45594', 'html_url': 'https://github.com/pandas-dev/pandas/pull/45594', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/45594.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/45594.patch', 'merged_at': None}","Test stubs originally authored by Joanna Sendorek, Zbigniew Królikowski and pandas_stubs contributors: https://github.com/VirtusLab/pandas-stubs/graphs/contributors

Adapted to pandas needs by Torsten Wörtwein

**CI change:**

Due to incompatibility of isort with black in terms of import order (former with default configuration) I've reconfigured isort to work with black profile:

```
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: [""--profile"", ""black""]
```

- [x] closes #45252
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45594/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45594/timeline,
28,https://api.github.com/repos/pandas-dev/pandas/issues/45593,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45593/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45593/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45593/events,https://github.com/pandas-dev/pandas/issues/45593,1112867034,I_kwDOAA0YD85CVQDa,45593,BUG: Cannot assign values to DataFrame using mask after previous multi-column `__setitem__` value assignment,"{'login': 'zkrolikowski-vl', 'id': 63653095, 'node_id': 'MDQ6VXNlcjYzNjUzMDk1', 'avatar_url': 'https://avatars.githubusercontent.com/u/63653095?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zkrolikowski-vl', 'html_url': 'https://github.com/zkrolikowski-vl', 'followers_url': 'https://api.github.com/users/zkrolikowski-vl/followers', 'following_url': 'https://api.github.com/users/zkrolikowski-vl/following{/other_user}', 'gists_url': 'https://api.github.com/users/zkrolikowski-vl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zkrolikowski-vl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zkrolikowski-vl/subscriptions', 'organizations_url': 'https://api.github.com/users/zkrolikowski-vl/orgs', 'repos_url': 'https://api.github.com/users/zkrolikowski-vl/repos', 'events_url': 'https://api.github.com/users/zkrolikowski-vl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zkrolikowski-vl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-01-24T16:25:03Z,2022-01-26T00:41:13Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
df = pd.DataFrame(data={'a': [1], 'b': [1]})
df[['a', 'b']] = [[2, 2]]
select_df = pd.DataFrame({'a': [True], 'b': [False]})
df[select_df] = [3, 3]
```


### Issue Description

It's impossible to assign values to DataFrame using a DataFrame mask if the source DataFrame's values were assigned in a multi-column fashion by using `__setitem__`.

This seems to be a regression in pandas 1.4.0rc0 as the code is running fine under 1.3.5 or possibly an udocumented change - unless I missed this being mentioned in the changelog.

Comparatively the following code works:
```
df = pd.DataFrame(data={'a': [1], 'b': [1]})
select_df = pd.DataFrame({'a': [True], 'b': [False]})
df[select_df] = [3, 3]
```

Moreover the following assignment variants don't cause any problems:
```
df.loc[:, ['a', 'b']] = (1,2)
df.loc[0, ['a', 'b']] = (1,2)
```

I apologize if this issue is known under different keywords.
<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/frame.py"", line 3642, in __setitem__
    self._setitem_frame(key, value)
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/frame.py"", line 3765, in _setitem_frame
    self._where(-key, value, inplace=True)
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/generic.py"", line 9155, in _where
    new_data = self._mgr.putmask(mask=cond, new=other, align=align)
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/internals/managers.py"", line 347, in putmask
    return self.apply(
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/internals/managers.py"", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/internals/blocks.py"", line 976, in putmask
    putmask_without_repeat(values.T, mask, new)
  File ""/opt/anaconda3/envs/base38/lib/python3.8/site-packages/pandas/core/array_algos/putmask.py"", line 147, in putmask_without_repeat
    raise ValueError(""cannot assign mismatch length to masked array"")
ValueError: cannot assign mismatch length to masked array
```
</details>

### Expected Behavior

DataFrame should have it's values assigned based on the mask. An REPL example follows:
```
>>> df = pd.DataFrame(data={'a': [1], 'b': [1]})
>>> df[['a', 'b']] = [[2, 2]]
>>> select_df = pd.DataFrame({'a': [True], 'b': [False]})
>>> df[select_df] = [3, 3]
>>> df
   a  b
0  3  2
```

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.2.0
Version          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 47.3.1
Cython           : None
pytest           : 6.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.3.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45593/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45593/timeline,
29,https://api.github.com/repos/pandas-dev/pandas/issues/45591,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/45591/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/45591/comments,https://api.github.com/repos/pandas-dev/pandas/issues/45591/events,https://github.com/pandas-dev/pandas/issues/45591,1112774104,I_kwDOAA0YD85CU5XY,45591,BUG: Cut fails when number of bins is more than 102 on a 32-bit machine.,"{'login': 'QubinX', 'id': 98165354, 'node_id': 'U_kgDOBdniag', 'avatar_url': 'https://avatars.githubusercontent.com/u/98165354?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/QubinX', 'html_url': 'https://github.com/QubinX', 'followers_url': 'https://api.github.com/users/QubinX/followers', 'following_url': 'https://api.github.com/users/QubinX/following{/other_user}', 'gists_url': 'https://api.github.com/users/QubinX/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/QubinX/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/QubinX/subscriptions', 'organizations_url': 'https://api.github.com/users/QubinX/orgs', 'repos_url': 'https://api.github.com/users/QubinX/repos', 'events_url': 'https://api.github.com/users/QubinX/events{/privacy}', 'received_events_url': 'https://api.github.com/users/QubinX/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-01-24T15:11:57Z,2022-01-25T09:26:24Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import numpy as np
import pandas as pd

number = 102
example = pd.cut(x=pd.Series(range(100)), bins=pd.Series(range(number))) 
print(example)
```


### Issue Description

The above code works as expected when number is <102, but fails when number >=102. This only occurs on a 32 bit machine. When this is run on a 64 bit machine, it does not fail.

The traceback when this fails is:
Traceback (most recent call last):

  File ""C:\Users\careyc\OneDrive - Harman Technology Ltd\Python\densitometer\cutbugtest.py"", line 10, in <module>
    example = pd.cut(x=pd.Series(range(100)), bins=pd.Series(range(102)))

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\reshape\tile.py"", line 287, in cut
    fac, bins = _bins_to_cuts(

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\reshape\tile.py"", line 450, in _bins_to_cuts
    labels = Categorical(

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py"", line 456, in __init__
    codes = _get_codes_for_values(values, dtype.categories)

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py"", line 2666, in _get_codes_for_values
    return coerce_indexer_dtype(categories.get_indexer_for(values), categories)

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\indexes\base.py"", line 5274, in get_indexer_for
    if self._index_as_unique:

  File ""pandas\_libs\properties.pyx"", line 37, in pandas._libs.properties.CachedProperty.__get__

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\indexes\interval.py"", line 727, in _index_as_unique
    return not self.is_overlapping and self._engine._na_count < 2

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\indexes\interval.py"", line 454, in is_overlapping
    return self._engine.is_overlapping

  File ""pandas\_libs\properties.pyx"", line 37, in pandas._libs.properties.CachedProperty.__get__

  File ""C:\Users\careyc\Anaconda3\lib\site-packages\pandas\core\indexes\interval.py"", line 325, in _engine
    return IntervalTree(left, right, closed=self.closed)

  File ""pandas\_libs\intervaltree.pxi"", line 77, in pandas._libs.interval.IntervalTree.__init__

  File ""pandas\_libs\intervaltree.pxi"", line 1025, in pandas._libs.interval.Int64ClosedRightIntervalNode.__init__

  File ""pandas\_libs\intervaltree.pxi"", line 1069, in pandas._libs.interval.Int64ClosedRightIntervalNode.new_child_node

  File ""pandas\_libs\intervaltree.pxi"", line 196, in pandas._libs.interval.take

TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

### Expected Behavior

Would expect the output to be:
0              NaN
1       (0.0, 1.0]
2       (1.0, 2.0]
3       (2.0, 3.0]
4       (3.0, 4.0]
.....    
95    (94.0, 95.0]
96    (95.0, 96.0]
97    (96.0, 97.0]
98    (97.0, 98.0]
99    (98.0, 99.0]
100 (99.0, 100.0]
Length: 101, dtype: category
Categories (101, interval[int64, right]): [(0, 1] < (1, 2] < (2, 3] < (3, 4] ... (96, 97] <
                                           (97, 98] < (98, 99] < (99, 100] < (100, 101]]


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.12.final.0
python-bits      : 32
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : x86
processor        : x86 Family 6 Model 23 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : English_United Kingdom.1252

pandas           : 1.3.5
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.25
pytest           : 6.2.4
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2022.01.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.51.2

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45591/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/45591/timeline,
